// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ERC6551AccountLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ERC6551AccountLib";
  readonly sourceName: "contracts/lib/ERC6551AccountLib.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200b9087ae37042ba1725d7683b0e1ce462f7a8c41cd194046adcc1985f54e698664736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200b9087ae37042ba1725d7683b0e1ce462f7a8c41cd194046adcc1985f54e698664736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lib/ERC6551AccountLib.sol";
  readonly buildInfoId: "solc-0_8_28-9bf3c53d5903294910ddae44f80368016655cef3";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ERC6551AccountLib"]: ERC6551AccountLib$Type;
    ["contracts/lib/ERC6551AccountLib.sol:ERC6551AccountLib"]: ERC6551AccountLib$Type;
  }
}