// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ERC6551AccountLib$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ERC6551AccountLib";
  readonly sourceName: "contracts/lib/ERC6551AccountLib.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fcab21a3e5fa4e4b016a1091c6073a35b501b541e90c1101549a7c832a7160ed64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220fcab21a3e5fa4e4b016a1091c6073a35b501b541e90c1101549a7c832a7160ed64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lib/ERC6551AccountLib.sol";
  readonly buildInfoId: "solc-0_8_28-4bc73337f03207b2dc3da90a7e4e5d78aabe7052";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ERC6551AccountLib"]: ERC6551AccountLib$Type;
    ["contracts/lib/ERC6551AccountLib.sol:ERC6551AccountLib"]: ERC6551AccountLib$Type;
  }
}